BEGIN TRANSACTION;


DROP TABLE IF EXISTS search;
DROP TABLE IF EXISTS apartment;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS users
 (id BIGSERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);



CREATE TABLE IF NOT EXISTS search
  (id BIGSERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  query JSON
);

CREATE TABLE IF NOT EXISTS apartment
 (id BIGSERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id),
price INTEGER,
beds VARCHAR(255),
bath (VARCHAR(255)
);


COMMIT;
